### ISSUE TITLE
How to set custom Chart/QuoteFeed Symbol

### ISSUE THREAD

**Issue by ToddAlvord** [ChartIQ/chartiq-react-app#2]
I have the chart working and loading but when I provide my custom quote feed it requests resources from our backend based on the chart's symbol. When using a custom quotefeed the symbol is still set to AAPL. How can I change the symbol? I'd like to be able to do this programmatically through either the constructor or the preferences, if possible.

**Comment by RMcNeely** [comment]
Hi Todd,

You can set the chart symbol thru the UIContext or by calling `CIQ.ChartEngine#newChart` but right now the chart does not support setting the default symbol via the constructor. You can also change the default loaded symbol if you would like to edit `src/components/Features/ChartLookup.jsx`. 

If you need any help with your custom quoteFeed itself please reach out to [support@chartiq.com](mailto:support@chartiq.com)
